# Generated by Django 5.0.2 on 2024-03-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Recipe_instructions',
            field=models.TextField(default=''),
        ),
    ]
